### ISSUE TITLE
Find a fallback datastorage for the system

### ISSUE THREAD

**Issue by Laberbear** [OpServ-Monitoring/opserv-backend#11]
While Vedis is great and will probably work most of the times, it is another dependency that could cause the system to not function at all on certain configurations.

Maybe we should search for a fallback method of saving data, that maybe is slower and not as efficient but atleast works everytime. (I'm thinking of csv or something as simple)

**Comment by Laberbear** [comment]
Even a "Null" Fallback would be sufficient for now (e.g. just discarding all the save-to-db calls and telling the frontend, that there is now history data)

**Comment by EndzeitBegins** [comment]
As we're going with SQLite as embedded database system there seems to be no need for a fallback solution as it is a well proven part of the python ecosystem. 
Any errors will most likely occur due to missing permissions to write on the disk and not SQLite itself which would make any fallback for permanent storage opsolete.

Nonetheless there should be mechanisms to provide a clue through the apis in case an error should occur.
